# Generated by Django 5.1.15 on 2026-10-01 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteAdministracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.DateField(unique=True, verbose_name='Semana (lunes)')),
                ('entregado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tarde', models.BooleanField(default=False, verbose_name='Entregado tarde')),
                ('plantilla_total', models.PositiveIntegerField(default=0, help_text='Personas activas al viernes', verbose_name='Plantilla total al cierre')),
                ('altas', models.PositiveIntegerField(default=0, verbose_name='Altas')),
                ('bajas_renuncia', models.PositiveIntegerField(default=0, verbose_name='Bajas por renuncia')),
                ('bajas_despido', models.PositiveIntegerField(default=0, verbose_name='Bajas por despido')),
                ('bajas_abandono', models.PositiveIntegerField(default=0, verbose_name='Bajas por abandono')),
                ('bajas_otro', models.PositiveIntegerField(default=0, verbose_name='Bajas por otro motivo')),
                ('incap_enfermedad', models.PositiveIntegerField(default=0, verbose_name='Incapacidades por enfermedad general')),
                ('incap_riesgo', models.PositiveIntegerField(default=0, verbose_name='Incapacidades por riesgo de trabajo')),
                ('incap_maternidad', models.PositiveIntegerField(default=0, verbose_name='Incapacidades por maternidad')),
                ('dias_incapacidad', models.PositiveIntegerField(default=0, help_text='Suma de días de todas las incapacidades de la semana', verbose_name='Días de incapacidad acumulados')),
                ('vac_operador', models.PositiveIntegerField(default=0, verbose_name='Vacantes de operador')),
                ('vac_mecanico', models.PositiveIntegerField(default=0, verbose_name='Vacantes de mecánico')),
                ('vac_administrativo', models.PositiveIntegerField(default=0, verbose_name='Vacantes administrativas')),
                ('vac_otro', models.PositiveIntegerField(default=0, verbose_name='Otras vacantes')),
                ('vaca_adm_h', models.PositiveIntegerField(default=0, verbose_name='Administración: hombres')),
                ('vaca_adm_m', models.PositiveIntegerField(default=0, verbose_name='Administración: mujeres')),
                ('vaca_ops_h', models.PositiveIntegerField(default=0, verbose_name='Operaciones: hombres')),
                ('vaca_ops_m', models.PositiveIntegerField(default=0, verbose_name='Operaciones: mujeres')),
                ('cap_en_curso', models.PositiveIntegerField(default=0, verbose_name='Personal en capacitación')),
                ('cap_liberados', models.PositiveIntegerField(default=0, verbose_name='Liberados')),
                ('cap_bajas', models.PositiveIntegerField(default=0, verbose_name='Bajas en capacitación')),
                ('capturado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reporte de Administración',
                'verbose_name_plural': 'reportes de Administración',
                'ordering': ['-semana'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReporteJuridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.DateField(unique=True, verbose_name='Semana (lunes)')),
                ('entregado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tarde', models.BooleanField(default=False, verbose_name='Entregado tarde')),
                ('aud_ccl', models.PositiveIntegerField(default=0, verbose_name='Centro de Conciliación Laboral del Estado de Qro.')),
                ('aud_tca', models.PositiveIntegerField(default=0, verbose_name='Tribunal de Conciliación y Arbitraje del Estado de Qro.')),
                ('aud_juzgados', models.PositiveIntegerField(default=0, verbose_name='Juzgados Laborales del Estado de Qro.')),
                ('siniestros', models.PositiveIntegerField(default=0, verbose_name='Número de siniestros')),
                ('resp_propia', models.PositiveIntegerField(default=0, verbose_name='Responsabilidad de la empresa')),
                ('resp_tercero', models.PositiveIntegerField(default=0, verbose_name='Responsabilidad de terceros')),
                ('resp_compartida', models.PositiveIntegerField(default=0, verbose_name='Responsabilidad compartida')),
                ('resp_proceso', models.PositiveIntegerField(default=0, verbose_name='En determinación')),
                ('les_verde', models.PositiveIntegerField(default=0, verbose_name='Código verde')),
                ('les_amarillo', models.PositiveIntegerField(default=0, verbose_name='Código amarillo')),
                ('les_rojo', models.PositiveIntegerField(default=0, verbose_name='Código rojo')),
                ('les_negro', models.PositiveIntegerField(default=0, verbose_name='Código negro')),
                ('polizas_activadas', models.PositiveIntegerField(default=0, verbose_name='Activaciones de póliza')),
                ('capturado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reporte Jurídico',
                'verbose_name_plural': 'reportes Jurídicos',
                'ordering': ['-semana'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReporteOperaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.DateField(unique=True, verbose_name='Semana (lunes)')),
                ('entregado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('tarde', models.BooleanField(default=False, verbose_name='Entregado tarde')),
                ('unidades_disponibles', models.PositiveIntegerField(default=0, help_text='Unidades que salieron a ruta / en condiciones de operar', verbose_name='Unidades activas')),
                ('inhab_taller', models.PositiveIntegerField(default=0, help_text='Mantenimiento preventivo o correctivo', verbose_name='Inactivas por taller')),
                ('inhab_siniestro', models.PositiveIntegerField(default=0, verbose_name='Inactivas por siniestro')),
                ('inhab_documentacion', models.PositiveIntegerField(default=0, help_text='Permisos, verificación, placas, etc.', verbose_name='Inactivas por documentación')),
                ('inhab_otro', models.PositiveIntegerField(default=0, verbose_name='Inactivas por otro motivo')),
                ('corridas_programadas', models.PositiveIntegerField(default=0, help_text='Según el plan operativo de la semana', verbose_name='Corridas programadas')),
                ('corridas_realizadas', models.PositiveIntegerField(default=0, verbose_name='Corridas realizadas')),
                ('litros', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Litros')),
                ('cargas', models.PositiveIntegerField(default=0, help_text='Número de cargas realizadas en la semana', verbose_name='Cargas de combustible')),
                ('consumo_promedio', models.DecimalField(decimal_places=2, default=0, help_text='Kilómetros por litro promedio de la flota', max_digits=6, verbose_name='Consumo promedio (km/L)')),
                ('cc_recibidas', models.PositiveIntegerField(default=0, verbose_name='Llamadas recibidas')),
                ('cc_atendidas', models.PositiveIntegerField(default=0, verbose_name='Llamadas atendidas')),
                ('cc_quejas', models.PositiveIntegerField(default=0, verbose_name='Quejas registradas')),
                ('capturado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reporte de Operaciones',
                'verbose_name_plural': 'reportes de Operaciones',
                'ordering': ['-semana'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadesRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(max_length=60, verbose_name='Ruta')),
                ('unidades', models.PositiveIntegerField(default=0, verbose_name='Unidades')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='core.reporteoperaciones')),
            ],
            options={
                'verbose_name': 'unidades por ruta',
                'verbose_name_plural': 'unidades por ruta',
                'ordering': ['ruta'],
                'unique_together': {('reporte', 'ruta')},
            },
        ),
    ]
