# Generated by Django 5.1.15 on 2026-10-01 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def perfiles_existentes(apps, schema_editor):
    """Usuarios que ya existían: los directores deberán cambiar su contraseña; los superusuarios no."""
    User = apps.get_model(*settings.AUTH_USER_MODEL.split("."))
    Perfil = apps.get_model("core", "Perfil")
    for u in User.objects.all():
        Perfil.objects.get_or_create(user=u, defaults={"debe_cambiar_clave": not u.is_superuser})


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe_cambiar_clave', models.BooleanField(default=True, help_text='Márcalo cuando le asignes o restablezcas una contraseña temporal.', verbose_name='Debe cambiar su contraseña al entrar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfil',
            },
        ),
        migrations.RunPython(perfiles_existentes, migrations.RunPython.noop),
    ]
