# Generated by Django 5.1.15 on 2026-10-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_unidades_inactivas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporteoperaciones',
            name='cargas',
        ),
        migrations.RemoveField(
            model_name='reporteoperaciones',
            name='consumo_promedio',
        ),
        migrations.RemoveField(
            model_name='reporteoperaciones',
            name='corridas_programadas',
        ),
        migrations.RemoveField(
            model_name='reporteoperaciones',
            name='corridas_realizadas',
        ),
        migrations.RemoveField(
            model_name='reporteoperaciones',
            name='unidades_inactivas',
        ),
        migrations.AddField(
            model_name='reporteoperaciones',
            name='aux_rutas',
            field=models.PositiveIntegerField(default=0, help_text='Auxiliares que se subieron a rutas en la semana', verbose_name='Auxiliares'),
        ),
        migrations.AddField(
            model_name='reporteoperaciones',
            name='coord_rutas',
            field=models.PositiveIntegerField(default=0, help_text='Coordinadores que se subieron a rutas en la semana', verbose_name='Coordinadores'),
        ),
        migrations.AddField(
            model_name='reporteoperaciones',
            name='sup_rutas',
            field=models.PositiveIntegerField(default=0, help_text='Supervisores que se subieron a rutas en la semana', verbose_name='Supervisores'),
        ),
        migrations.AddField(
            model_name='reporteoperaciones',
            name='unidades_plan',
            field=models.PositiveIntegerField(default=0, help_text='Unidades que salen según el plan operativo de la semana', verbose_name='Unidades en el plan operativo'),
        ),
        migrations.AlterField(
            model_name='reporteoperaciones',
            name='litros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Litros de diésel'),
        ),
    ]
