# Generated by Django 5.1.15 on 2026-10-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_plan_operativo_personal_rutas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporteadministracion',
            name='cap_bajas',
        ),
        migrations.RemoveField(
            model_name='reporteadministracion',
            name='dias_incapacidad',
        ),
        migrations.RemoveField(
            model_name='reporteadministracion',
            name='plantilla_total',
        ),
        migrations.AddField(
            model_name='reporteadministracion',
            name='plantilla_hombres',
            field=models.PositiveIntegerField(default=0, help_text='Hombres en plantilla al viernes', verbose_name='Hombres'),
        ),
        migrations.AddField(
            model_name='reporteadministracion',
            name='plantilla_mujeres',
            field=models.PositiveIntegerField(default=0, help_text='Mujeres en plantilla al viernes', verbose_name='Mujeres'),
        ),
    ]
