# Generated by Django 5.1.15 on 2026-10-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_personal_por_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportejuridico',
            name='resp_compartida',
        ),
        migrations.RemoveField(
            model_name='reportejuridico',
            name='resp_proceso',
        ),
        migrations.RemoveField(
            model_name='reportejuridico',
            name='resp_propia',
        ),
        migrations.RemoveField(
            model_name='reportejuridico',
            name='resp_tercero',
        ),
        migrations.RemoveField(
            model_name='reportejuridico',
            name='siniestros',
        ),
        migrations.AddField(
            model_name='reportejuridico',
            name='sin_no_responsable',
            field=models.PositiveIntegerField(default=0, help_text='Siniestros en los que la empresa no resultó responsable', verbose_name='No responsable'),
        ),
        migrations.AddField(
            model_name='reportejuridico',
            name='sin_responsable',
            field=models.PositiveIntegerField(default=0, help_text='Siniestros en los que la empresa resultó responsable', verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='reportejuridico',
            name='les_amarillo',
            field=models.PositiveIntegerField(default=0, help_text='Lesiones moderadas', verbose_name='Código amarillo'),
        ),
        migrations.AlterField(
            model_name='reportejuridico',
            name='les_negro',
            field=models.PositiveIntegerField(default=0, help_text='Personas fallecidas', verbose_name='Código negro'),
        ),
        migrations.AlterField(
            model_name='reportejuridico',
            name='les_rojo',
            field=models.PositiveIntegerField(default=0, help_text='Lesiones graves', verbose_name='Código rojo'),
        ),
        migrations.AlterField(
            model_name='reportejuridico',
            name='les_verde',
            field=models.PositiveIntegerField(default=0, help_text='Lesiones leves', verbose_name='Código verde'),
        ),
    ]
