# Generated by Django 5.1.15 on 2026-10-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_siniestros_responsabilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteoperaciones',
            name='q_frecuencia',
            field=models.PositiveIntegerField(default=0, verbose_name='Frecuencia'),
        ),
        migrations.AddField(
            model_name='reporteoperaciones',
            name='q_imprudente',
            field=models.PositiveIntegerField(default=0, verbose_name='Manejo imprudente'),
        ),
        migrations.AddField(
            model_name='reporteoperaciones',
            name='q_parada',
            field=models.PositiveIntegerField(default=0, verbose_name='No respeta parada'),
        ),
        migrations.AddField(
            model_name='reporteoperaciones',
            name='q_semaforo',
            field=models.PositiveIntegerField(default=0, verbose_name='No respeta semáforo'),
        ),
        migrations.AlterField(
            model_name='reporteoperaciones',
            name='cc_quejas',
            field=models.PositiveIntegerField(default=0, help_text='Total de quejas de la semana', verbose_name='Quejas registradas'),
        ),
    ]
