# Generated by Django 5.1.15 on 2026-10-05 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_motivos_queja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporteoperaciones',
            name='q_semaforo',
        ),
    ]
