# Generated by Django 5.1.15 on 2026-10-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bajas_defuncion_vacantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteoperaciones',
            name='coord_rutas',
            field=models.PositiveIntegerField(default=0, help_text='Encargados que se subieron a rutas en la semana', verbose_name='Encargados'),
        ),
    ]
