# Generated by Django 5.1.15 on 2026-10-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_encargados_rutas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporteoperaciones',
            name='unidades_plan',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Promedio diario de unidades que salieron a ruta de lunes a viernes', max_digits=6, verbose_name='Promedio de unidades que salieron'),
        ),
    ]
