# Generated by Django 5.2.17 on 2026-10-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_promedio_plan_operativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportejuridico',
            name='sin_no_dimensional',
            field=models.PositiveIntegerField(default=0, help_text='Siniestros no dimensionales', verbose_name='No dimensional'),
        ),
    ]
