# Generated by Django 5.2.17 on 2026-10-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_siniestro_no_dimensional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportejuridico',
            name='sin_no_dimensional',
            field=models.PositiveIntegerField(default=0, help_text='Siniestros no dimensionar', verbose_name='No dimensionar'),
        ),
    ]
